--- 
abstract: manage linear pipelines of data filters
author: James Smith
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-Pipeline
no_index: 
  directory: 
    - inc
    - t
requires: 
  Moose: 0.43
tests: t/*.t
version: 0.01
